# Generated by Django 2.1.2 on 2018-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twowheeler',
            name='Model_Info',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twowheeler',
            name='Model_img',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twowheeler',
            name='Price_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twowheeler',
            name='Price_before',
            field=models.IntegerField(default=0),
        ),
    ]
