# Generated by Django 2.1.2 on 2018-12-29 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0004_auto_20181219_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='twowheeler',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twowheeler',
            name='Company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='twowheeler',
            name='Model_Info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='twowheeler',
            name='Model_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
