# Generated by Django 2.1.2 on 2019-01-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0006_auto_20190126_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twowheeler',
            name='Model_img',
            field=models.ImageField(blank=True, upload_to='bike_img'),
        ),
    ]
