# Generated by Django 2.1.2 on 2019-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0007_auto_20190127_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(max_length=50)),
            ],
        ),
    ]
