# Generated by Django 2.1.2 on 2019-02-09 13:34

import bike.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0008_trialtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='twowheeler',
            name='Description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='twowheeler',
            name='Km_Image',
            field=models.ImageField(blank=True, upload_to='bike_img'),
        ),
        migrations.AddField(
            model_name='twowheeler',
            name='Left_side',
            field=models.ImageField(blank=True, upload_to='bike_img'),
        ),
        migrations.AddField(
            model_name='twowheeler',
            name='Rc_book',
            field=models.ImageField(blank=True, upload_to='bike_img'),
        ),
        migrations.AddField(
            model_name='twowheeler',
            name='Right_side',
            field=models.ImageField(blank=True, upload_to='bike_img'),
        ),
        migrations.AddField(
            model_name='twowheeler',
            name='Total_km',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trialtest',
            name='test1',
            field=models.CharField(max_length=50, validators=[bike.models.validate_com]),
        ),
    ]
