# Generated by Django 2.1.2 on 2019-02-10 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0009_auto_20190209_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twowheeler',
            name='Model_Info',
        ),
    ]
