# Generated by Django 2.1.2 on 2019-02-10 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0010_remove_twowheeler_model_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twowheeler',
            name='user',
        ),
        migrations.AddField(
            model_name='twowheeler',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
