# Generated by Django 2.1.2 on 2019-02-10 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0011_auto_20190210_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twowheeler',
            name='user',
        ),
        migrations.AddField(
            model_name='twowheeler',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
