# Generated by Django 2.1.2 on 2019-02-10 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0012_auto_20190210_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twowheeler',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
