# Generated by Django 2.1.2 on 2019-02-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0013_auto_20190210_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='twowheeler',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
