# Generated by Django 2.0.5 on 2019-02-10 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0014_twowheeler_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twowheeler',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
