# Generated by Django 2.0.5 on 2019-02-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0016_auto_20190215_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='twowheeler',
            name='Documents_Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='twowheeler',
            name='Brakes',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='twowheeler',
            name='Location',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='twowheeler',
            name='Overall',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='twowheeler',
            name='Suspension',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
    ]
