# Generated by Django 2.1.2 on 2018-12-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181229_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai')], max_length=50),
        ),
    ]
