# Generated by Django 2.1.2 on 2019-02-09 13:34

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190126_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='', max_length=200, validators=[home.models.validate_com]),
        ),
    ]
