# Generated by Django 2.0.5 on 2019-02-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190215_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Profile_image',
            field=models.ImageField(blank=True, upload_to='imgas'),
        ),
    ]
